# feature_request_flow.py
# This file implements the feature request flow, including planner, executor, and main agent logic for feature research and competitor analysis.
from agents import Agent, Runner, function_tool
import pandas as pd
import asyncio
import json

from dotenv import load_dotenv
import os
from mcp_servers.mcp_slack import send_slack_message


load_dotenv()

@function_tool
def print_hello_feature_request(review_text: str):
    print("Creating Jira Feature Request...")
    print(f"Feature request review: {review_text}")
    return json.dumps({"classification": "feature", "result": review_text})

# --- LLM-as-planner architecture ---

# 1. Planner agent (gpt-4o): creates a research plan
planner_agent = Agent(
    name="Feature Research Planner",
    instructions=(
        "You are a research planning assistant. Your task is to create a step-by-step research plan to investigate whether competing apps offer a given feature.\n\n"
        "First, list all well-known competitors for the app mentioned in the request (e.g., for Viber: WhatsApp, Telegram, Signal, Facebook Messenger, WeChat, LINE, etc).\n\n"
        "Next, select the top 3 most relevant competitors from that list and explain your reasoning for the selection.\n\n"
        "Then, outline steps to check if each of the top 3 competitors offers the feature. Include steps for gathering information and summarizing the results.\n\n"
        "Format your response as a numbered list of clear, specific steps (e.g., '1. List all competitors... 2. Select top 3... 3. Search for...').\n\n"
        "Only return the numbered list. Do not include explanations, JSON, or additional formatting."
    ),
    tools=[],
    #model="gpt-4o-mini"
    model="gpt-4o"
)

# 2. Executor agent (gpt-4o-mini): executes the plan
executor_agent = Agent(
    name="Feature Research Executor",
    instructions=(
        "You are an executor bot. You receive a research plan (list of steps) and a feature description. "
        "For each step, simulate or perform the research, and collect findings. "
        "When listing competitors, provide the full list and then clearly indicate the top 3 selected competitors and your reasoning. "
        "For the rest of the research, focus on the top 3. "
        "At the end, return a competitor report and feature detail as a JSON object with keys: classification, all_competitors, top_3_competitors_with_reasoning, competitor_report, feature_detail. "
        "Do not add any extra text."
    ),
    tools=[],
    model="gpt-4o-mini"
)

def send_feature_to_slack(feature_info: str):
    """
    Placeholder for sending feature details to Slack. For now, just print to terminal.
    """
    print("[SLACK PLACEHOLDER] Sending feature info to Slack:")
    print(feature_info)

@function_tool
async def research_competitors(feature_description: str):
    """
    Uses a planner bot to create a research plan, then an executor bot to execute it and return a structured competitor report and feature detail.
    """
    # Step 1: Planner creates a plan
    planner_prompt = (
        f"Feature request: {feature_description}\n"
        "Create a step-by-step research plan to determine if competitors have similar features."
    )
    plan_result = await Runner.run(planner_agent, planner_prompt)
    print("[DEBUG] Research plan generated by planner:")
    print(plan_result.final_output)
    try:
        plan_steps = json.loads(plan_result.final_output)
    except Exception:
        # Fallback: try to parse as a numbered list
        plan_steps = [line.strip(" .") for line in plan_result.final_output.split("\n") if line.strip()]
    # Step 2: Executor executes the plan
    executor_prompt = json.dumps({
        "feature_description": feature_description,
        "plan": plan_steps
    })
    exec_result = await Runner.run(executor_agent, executor_prompt)

    # Step 3: Also print to terminal
    print(exec_result.final_output)
    
    # Step 4: Send result to Slack (via MCP)
    print("[SLACK PLACEHOLDER] Sending feature info to Slack:")
    slack_channel = os.getenv("SLACK_CHANNEL", "#general")
    await send_slack_message(slack_channel, exec_result.final_output)

    return exec_result.final_output

feature_request_agent = Agent(
    name = "Feature Request Agent",
    instructions = (
        "You are a feature request agent. "
        "When you receive a feature request, you must call the research_competitors tool. "
        "The research_competitors tool will use a planner bot to create a research plan, and an executor bot to execute the plan. "
        "You must return ONLY the tool's result as your final output, which should include a competitor report and feature detail. "
        "Do not add any extra text."
    ),
    #tools=[print_hello_feature_request],  # For testing
    tools=[research_competitors],
    model="gpt-4o-mini"
)

if __name__ == "__main__":
    import asyncio
    async def main():
        sample_feature_request = "I would like a new feature that allows me to add a new contact to my address book."
        print(f"Testing feature_request_agent with input: {sample_feature_request}")
        result = await Runner.run(feature_request_agent, sample_feature_request)
        print("Agent final output:", result.final_output)
    asyncio.run(main())
