# feature_request_flow.py
# This file implements the feature request flow, including planner, executor, and main agent logic for feature research and competitor analysis.
from agents import Agent, Runner, function_tool
import pandas as pd
import asyncio
import json

from dotenv import load_dotenv
import os
from mcp_servers.mcp_slack import send_slack_message


load_dotenv()

@function_tool
async def research_competitors(feature_description: str):
    """
    Uses a planner bot to create a research plan, then an executor bot to execute it and return a structured competitor report and feature detail.
    """

    # Step 1: Planner creates a plan
    planner_prompt = (
        f"Feature request: {feature_description}\n"
        "Create a step-by-step research plan to determine if competitors have similar features."
    )
    plan_result = await Runner.run(planner_agent, planner_prompt)
    print("[DEBUG] Research plan generated by planner:")
    print(plan_result.final_output)
    plan_steps = [line.strip(" .") for line in plan_result.final_output.split("\n") if line.strip()]

    # Step 2: Executor executes the plan
    executor_prompt = json.dumps({
        "feature_description": feature_description,
        "plan": plan_steps
    })
    exec_result = await Runner.run(executor_agent, executor_prompt)
    print("\n[DEBUG] Research result generated by executor:")
    print(exec_result.final_output)

    # Step 3: Save research plan and result to research_result.md
    md_path = os.path.join(os.path.dirname(__file__), "../research_result.md")
    with open(md_path, "a", encoding="utf-8") as f:
        f.write("\n---\n")
        f.write(f"## Feature Request\n{feature_description}\n\n")
        f.write("### Research Plan\n")
        f.write(plan_result.final_output + "\n\n")
        f.write("### Research Result\n")
        f.write(exec_result.final_output + "\n")

    # Step 4: Send result to Slack
    #send_slack_message(exec_result.final_output)

    return exec_result.final_output


# 1. Feature request agent: handles the feature request
feature_request_agent = Agent(
    name = "Feature Request Agent",
    instructions = (
        "You are a feature request agent. "
        "You are responsible for calling the research_competitors tool when handling a feature request. "
        "You must return ONLY the tool's result as your final output, which should include a competitor report and feature detail. "
        "Do not add any extra text."
    ),
    tools=[research_competitors],
    model="gpt-4o-mini"
)


# 2. Planner agent (gpt-4o): creates a research plan
planner_agent = Agent(
    name="Feature Research Planner",
    instructions=(
        "You are a research planning assistant. Your task is to create a step-by-step research plan to investigate whether competing apps offer a given feature.\n\n"
        "First, list all well-known competitors for Viber (instant messaging app).\n\n"
        "Next, select the top 3 most relevant competitors from that list and explain your reasoning for the selection.\n\n"
        "Then, outline steps to check if each of the top 3 competitors offers the feature. Include steps for gathering information and summarizing the results.\n\n"
        "Format your response as a numbered list of clear, specific steps (e.g., '1. List all competitors... 2. Select top 3... 3. Search for...').\n\n"
        "Only return the numbered list. Do not include explanations, JSON, or additional formatting."
    ),
    #model="gpt-4o-mini"
    model="gpt-4o"
)


# 3. Executor agent (gpt-4o-mini): executes the plan
executor_agent = Agent(
    name="Feature Research Executor",
    instructions=(
        "You are an executor bot. You receive a research plan (list of steps) and a feature description. "
        "For each step, simulate or perform the research, and collect findings. "
        "When listing competitors, provide the full list and then clearly indicate the top 3 selected competitors and your reasoning. "
        "For the rest of the research, focus on the top 3. "
        "At the end, return your output as plain text with the following sections, each clearly labeled: "
        "Classification, All Competitors, Top 3 Competitors with Reasoning, Competitor Report, Feature Detail. "
        "Do not use JSON or any other structured data format. Do not add any extra text."
    ),
    model="gpt-4o-mini"
)



if __name__ == "__main__":
    import asyncio
    async def main():
        sample_feature_request = "I would like a new feature that allows me to add a new contact to my address book."
        print(f"Testing feature_request_agent with input: {sample_feature_request}")
        result = await Runner.run(feature_request_agent, sample_feature_request)
        print("Agent final output:", result.final_output)
    asyncio.run(main())
